// #1
// If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
//Find the sum of all the multiples of 3 or 5 below 1000.

var arr = [];

for (var i = 1; i < 1000; i++) {
  if ((i % 3 === 0) || (i % 5 === 0)) {
    arr.push(i);
  }
}

var myTotal = arr.reduce(function(a, b) { return a + b; }, 0);

console.log(arr);
console.log(myTotal);

// #2
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

var fib = [1, 2];
var limit = 4000000;
var sum = 0;

for (var i=0; i < limit; i++) {
    var test = fib[i] + fib[i + 1];
    fib.push(test);
    var number = fib[i];;
    if (number < limit && number % 2 == 0) {
      var result = sum += number;
    }
}

console.log(result);